### ISSUE TITLE
Notifications with large amounts of text break notif box visually

### ISSUE THREAD

**Issue by SalbugVR** [Minty-Labs/WindowsXSO#1]
Notifications that contain large amounts of text break the XSO notification box, plus text gets cut off on top and bottom. Perhaps have text get truncated after a certain amount.

**Comment by MintLily** [comment]
I see that, it seems to be a limit within XSOverlay itself. I'll work in a fix for it soon.

**Comment by MintLily** [comment]
Hopefully my changes to [v1.2.0](https://github.com/Minty-Labs/WindowsXSO/releases/tag/1.2.0) helps with this. I will close this issue for now. If you still have issues, I'll reopen it.

**Comment by SalbugVR** [comment]
Looks like it's still happening actually.

![image](https://github.com/Minty-Labs/WindowsXSO/assets/24326270/e6563677-d898-4cf5-bdae-ef6c62c17075)

**Comment by MintLily** [comment]
I wonder if it is a limitation to XSOverlay itself. I'll have to ask around and/or continue to test it. I won't be able to do much of anything until the weekend of Nov 11th. So hopefully its not too big of an issue for you.

**Comment by SalbugVR** [comment]
It's not too big of an issue but I wanted to bring it up anyway. I'll see if I can raise this issue with Xiexe as well.

EDIT: [done.](https://github.com/Xiexe/XSOverlay-Issue-Tracker/issues/312)

**Comment by MintLily** [comment]
This issue seems that it will not be "fixed" any time soon. I can always re-open this in the future if needed.
